### ISSUE TITLE
Set default order for all models at once

### ISSUE THREAD

**Issue by sedubois** [XPBytes/administrate-default_order#6]
Instead of having to define the default order in every controller for every model separately, it would be great to be able to define it on the base admin controller with some reasonable default, e.g `id: :desc`. Then this could be overridden only in the controllers where some special default order is needed.

**Comment by SleeplessByte** [comment]
So basically `set default default_order`?

I personally really don't like that, because the implicitness makes it much harder for people to follow the flow and require readers to go up the inheritance chain (including any "mixins") to find the defaults and or potential overrides.

Is it such a bother / boilerplate to add the single line and be explicit? (I'm looking for understanding on my end 😄)

**Comment by sedubois** [comment]
OK I get your point. Anyway there's already a way to set a default order in Administrate by overriding the application controller's `order` method (see [here](https://github.com/thoughtbot/administrate/issues/442#issuecomment-488593459)). It's just that without this possibility I don't see the added value of this plugin as it allows to do less than what's possible by overriding administrate directly.

**Comment by SleeplessByte** [comment]
Except that this gem adds DSL to do it correctly for has-many tables,
whereas the order override becomes very cumbersome to do for nested fields.

**Comment by sedubois** [comment]
Yes, however the philosophy of administrate is to avoid DSLs (https://github.com/thoughtbot/administrate/#what-is-administrate).
